name: pdf_viewer_jk
description: A flutter plugin for viewing PDF files in mobile app (Android & iOS).
version: 2.0.1
repository: https://github.com/jawadsahil/pdf_viewer_jk
homepage: https://jawad.pro

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.2
  async: ^2.9.0
  flutter_cache_manager: ^3.3.0
  flutter_spinbox: ^0.11.0
  flutter_svg: ^1.1.6
  http: ^1.1.0
  path_provider: ^2.0.11
  path: ^1.8.2
  pool: ^1.5.1
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pro.jawad.pdf_viewer_jk
        pluginClass: PdfViewerJkPlugin
      ios:
        pluginClass: PdfViewerJkPlugin
